server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.chenzhaowu.superProject.bean
  configuration:    map-underscore-to-camel-case: true
logging:
  file:
    #项目根目录\my-log\mylog\spring.log
    #path: my-log/myLog
    #项目所在磁盘根目录\springboot\logging\my\spring.log    path: /springBoot/loggingspring:
#  messages: 
#    basename: login 
#spring.profiles.active=dev
  datasource:
    url: jdbc:mysql://localhost:3306/superproject?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid: 
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: wall,stat
      #connect-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: true
        login-username: admin
        login-password: password
      web-stat-filter:
        url-pattern: /*
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
      aop-patterns: com.chenzhaowu.superProject.*
      filter:
        stat: 
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            update-allow: true
            drop-table-allow: false
            insert-allow: true
            delete-allow: true